import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'

import styles from '../styles/Home.module.scss'
import Org from "../public/org.svg"
import Inde from "../public/inde.svg"


export default function Home() {
  const router=useRouter();
  const handleConnect=(type:string)=>{
    window.ethereum
    .request({ method: "eth_requestAccounts" })
    .then((res)=>{
      router.push({
          pathname:"/dashBoard",
          query:{
            mode:type
          }
        }
      )
    }).catch((err) => {
      if (err.code === 4001) {
        console.log("Please connect to MetaMask.");
      } else {
        console.error(err);
      }
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <div className={styles.card}>
          <Image 
            src={Org}
            alt="Organization"
          />
          <p>Organization / Issuer</p>
          <button className={styles.btn} onClick={()=>handleConnect("org")}>Connect</button>
       </div>
       <div className={styles.card}>
          <Image 
            src={Inde}
            alt="Individual"
          />
          <p>Individual</p>
          <button className={styles.btn} onClick={()=>handleConnect("inde")}>Connect</button>
       </div>
      </main>
    </div>
  )
}
